import createFetchClient, { type Middleware } from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript
import { isProblemDetails, ProblemDetailsError } from "./problem-details";

/**
 * Middleware that intercepts application/problem+json responses
 * and throws a typed ProblemDetailsError
 */
const problemDetailsMiddleware: Middleware = {
  async onResponse({ response }) {
    const contentType = response.headers.get("content-type");
    if (!response.ok && contentType?.includes("application/problem+json")) {
      const body = await response.json();
      if (isProblemDetails(body)) {
        throw new ProblemDetailsError(body);
      }
    }
    return undefined;
  },
};

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.VITE_API_BASE_URL || "/api",
  credentials: "include",
});

fetchClient.use(problemDetailsMiddleware);

const api = createClient(fetchClient);

export { api };
