/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authAppLayoutRouteRouteImport } from './routes/(auth)/_app-layout/route'
import { Route as authAppLayoutDashboardRouteImport } from './routes/(auth)/_app-layout/dashboard'
import { Route as authAppLayoutAdminUsersIndexRouteImport } from './routes/(auth)/_app-layout/admin/users/index'
import { Route as authAppLayoutAdminDepartmentsIndexRouteImport } from './routes/(auth)/_app-layout/admin/departments/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authAppLayoutRouteRoute = authAppLayoutRouteRouteImport.update({
  id: '/(auth)/_app-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authAppLayoutDashboardRoute = authAppLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authAppLayoutRouteRoute,
} as any)
const authAppLayoutAdminUsersIndexRoute =
  authAppLayoutAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => authAppLayoutRouteRoute,
  } as any)
const authAppLayoutAdminDepartmentsIndexRoute =
  authAppLayoutAdminDepartmentsIndexRouteImport.update({
    id: '/admin/departments/',
    path: '/admin/departments/',
    getParentRoute: () => authAppLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof authAppLayoutDashboardRoute
  '/admin/departments': typeof authAppLayoutAdminDepartmentsIndexRoute
  '/admin/users': typeof authAppLayoutAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof authAppLayoutDashboardRoute
  '/admin/departments': typeof authAppLayoutAdminDepartmentsIndexRoute
  '/admin/users': typeof authAppLayoutAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/(auth)/_app-layout': typeof authAppLayoutRouteRouteWithChildren
  '/(auth)/_app-layout/dashboard': typeof authAppLayoutDashboardRoute
  '/(auth)/_app-layout/admin/departments/': typeof authAppLayoutAdminDepartmentsIndexRoute
  '/(auth)/_app-layout/admin/users/': typeof authAppLayoutAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/admin/departments'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/admin/departments'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/(auth)/_app-layout'
    | '/(auth)/_app-layout/dashboard'
    | '/(auth)/_app-layout/admin/departments/'
    | '/(auth)/_app-layout/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  authAppLayoutRouteRoute: typeof authAppLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_app-layout': {
      id: '/(auth)/_app-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAppLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_app-layout/dashboard': {
      id: '/(auth)/_app-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authAppLayoutDashboardRouteImport
      parentRoute: typeof authAppLayoutRouteRoute
    }
    '/(auth)/_app-layout/admin/users/': {
      id: '/(auth)/_app-layout/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof authAppLayoutAdminUsersIndexRouteImport
      parentRoute: typeof authAppLayoutRouteRoute
    }
    '/(auth)/_app-layout/admin/departments/': {
      id: '/(auth)/_app-layout/admin/departments/'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof authAppLayoutAdminDepartmentsIndexRouteImport
      parentRoute: typeof authAppLayoutRouteRoute
    }
  }
}

interface authAppLayoutRouteRouteChildren {
  authAppLayoutDashboardRoute: typeof authAppLayoutDashboardRoute
  authAppLayoutAdminDepartmentsIndexRoute: typeof authAppLayoutAdminDepartmentsIndexRoute
  authAppLayoutAdminUsersIndexRoute: typeof authAppLayoutAdminUsersIndexRoute
}

const authAppLayoutRouteRouteChildren: authAppLayoutRouteRouteChildren = {
  authAppLayoutDashboardRoute: authAppLayoutDashboardRoute,
  authAppLayoutAdminDepartmentsIndexRoute:
    authAppLayoutAdminDepartmentsIndexRoute,
  authAppLayoutAdminUsersIndexRoute: authAppLayoutAdminUsersIndexRoute,
}

const authAppLayoutRouteRouteWithChildren =
  authAppLayoutRouteRoute._addFileChildren(authAppLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  authAppLayoutRouteRoute: authAppLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
