/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicRegisterRouteImport } from './routes/(public)/register'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as authLayoutRouteRouteImport } from './routes/(auth)/_layout/route'
import { Route as authLayoutDashboardRouteImport } from './routes/(auth)/_layout/dashboard'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRegisterRoute = publicRegisterRouteImport.update({
  id: '/(public)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRouteRoute = authLayoutRouteRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutDashboardRoute = authLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof publicAboutRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof authLayoutDashboardRoute
}
export interface FileRoutesByTo {
  '/about': typeof publicAboutRoute
  '/login': typeof publicLoginRoute
  '/register': typeof publicRegisterRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof authLayoutDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_layout': typeof authLayoutRouteRouteWithChildren
  '/(public)/about': typeof publicAboutRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/register': typeof publicRegisterRoute
  '/(public)/': typeof publicIndexRoute
  '/(auth)/_layout/dashboard': typeof authLayoutDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/login' | '/register' | '/' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/login' | '/register' | '/' | '/dashboard'
  id:
    | '__root__'
    | '/(auth)/_layout'
    | '/(public)/about'
    | '/(public)/login'
    | '/(public)/register'
    | '/(public)/'
    | '/(auth)/_layout/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRouteRoute: typeof authLayoutRouteRouteWithChildren
  publicAboutRoute: typeof publicAboutRoute
  publicLoginRoute: typeof publicLoginRoute
  publicRegisterRoute: typeof publicRegisterRoute
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/register': {
      id: '/(public)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout/dashboard': {
      id: '/(auth)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authLayoutDashboardRouteImport
      parentRoute: typeof authLayoutRouteRoute
    }
  }
}

interface authLayoutRouteRouteChildren {
  authLayoutDashboardRoute: typeof authLayoutDashboardRoute
}

const authLayoutRouteRouteChildren: authLayoutRouteRouteChildren = {
  authLayoutDashboardRoute: authLayoutDashboardRoute,
}

const authLayoutRouteRouteWithChildren = authLayoutRouteRoute._addFileChildren(
  authLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRouteRoute: authLayoutRouteRouteWithChildren,
  publicAboutRoute: publicAboutRoute,
  publicLoginRoute: publicLoginRoute,
  publicRegisterRoute: publicRegisterRoute,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
