import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: "/api",
});

const api = createClient(fetchClient);

export { api };
